char* imutCodCez(const char* str, int key);
void mutCezar(char* str, int key);
char* imutCodXor(const char* str, const char* key);
void mutCodXor(char* str, const char* key);
char* imutToUpper(const char* str);
void mutToUpper(char* str);
char* imutToLower(const char* str);
void mutToLower(char* str);
char* imutFilterSp(const char* str);
void mutFilterSp(char* str);
char* imutFilter(const char* str);
void mutFilter(char* str);
char* imutDelSp(const char* str);
void mutDelSp(char* str);
int ifNumbStr(const char* str);
int ifLettStr(const char* str);
